---
title: spc82.github.io
timezone: Europe/Madrid
collections:
  Analisis:
    title: An√°lisis
    output: true
  authors:
    title: Authors
    output: true
  medios:
    title: Medios
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    summary-text: ''
    authors: ''
    keywords: ''
    description: ''
    thumbnail-image: ''
    article-image: ''
    article-image-title: ''
    medios: ''
    link:
      url: ''
      title: ''
      author-medio: ''
      has-new-window: ''
name: vdos.com
exclude:
- LICENSE.txt
- README.md
- doc
data_dir: "./_data"
