---
title: spc82.github.io
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: vdos.com
exclude:
- LICENSE.txt
- README.md
- doc
data_dir: "./_data"
defaults:
  -
   scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      author: ""
      img: ""
      thumbnail: ""